ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-{{ env }}.amireddyravi.space
REDIS_HOST: redis-{{ env }}.amireddyravi.space
MYSQL_HOST: mysql-{{ env }}.amireddyravi.space
RABBITMQ_HOST: rabbitmq-{{ env }}.amireddyravi.space

CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.amireddyravi.space
USER_HOST: user.backend-alb-{{ env }}.amireddyravi.space
CART_HOST: cart.backend-alb-{{ env }}.amireddyravi.space
SHIPPING_HOST: shipping.backend-alb-{{ env }}.amireddyravi.space
PAYMENT_HOST: payment.backend-alb-{{ env }}.amireddyravi.space